'use strict';

const URGENCY_EMOJI = {
  'Act Now': '🔴',
  'Plan Ahead': '🟡',
  'Monitor': '🔵',
  'FYI': '⚪'
};

/**
 * Format a date string as "Month DD, YYYY".
 */
function formatDate(isoDate) {
  try {
    return new Date(isoDate).toLocaleDateString('en-US', {
      month: 'long', day: 'numeric', year: 'numeric'
    });
  } catch {
    return isoDate;
  }
}

/**
 * Generate the Markdown blog post for a given day's digest.
 *
 * @param {Array} scoredArticles - Sorted scored article objects
 * @param {object} meta - { date (ISO), totalScanned, totalPassed, sourceWarnings, runTimestamp }
 * @returns {string} Markdown content
 */
function generateMarkdownPost(scoredArticles, meta) {
  const date = meta.date || new Date().toISOString().split('T')[0];
  const displayDate = formatDate(date);
  const topScore = scoredArticles.length > 0 ? scoredArticles[0].impact_score : 0;
  const topArticles = scoredArticles.slice(0, 3);
  const moreArticles = scoredArticles.slice(3, 10);

  // Collect unique source names for footer
  const sourceNames = [...new Set(scoredArticles.map(a => a.source))].filter(Boolean);

  const lines = [];

  // Front matter
  lines.push('---');
  lines.push(`title: "SEM Intel Digest — ${displayDate}"`);
  lines.push(`date: ${date}`);
  lines.push('author: "SEM Intel Agent"');
  lines.push('tags: ["sem", "ppc", "google-ads", "microsoft-ads", "daily-digest"]');
  lines.push(`top_impact_score: ${topScore}`);
  if (scoredArticles.length > 0) {
    lines.push(`summary: "${scoredArticles[0].headline.replace(/"/g, "'")}"`);
  } else {
    lines.push('summary: "No significant SEM/PPC news today."');
  }
  lines.push('---');
  lines.push('');

  // Title
  lines.push(`# SEM Intel Digest — ${displayDate}`);
  lines.push('');
  lines.push(`*${meta.totalScanned || 0} sources scanned · ${meta.totalPassed || 0} articles analyzed · Top ${topArticles.length} curated*`);
  lines.push('');
  lines.push('---');
  lines.push('');

  if (scoredArticles.length === 0) {
    lines.push('No significant SEM/PPC news today. Check back tomorrow.');
    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push(`*Generated by SEM Intel Agent · Run: ${meta.runTimestamp}*`);
    return lines.join('\n');
  }

  // Top 3 stories — full card treatment
  for (let i = 0; i < topArticles.length; i++) {
    const article = topArticles[i];
    const emoji = URGENCY_EMOJI[article.urgency] || '⚪';

    lines.push(`## ${emoji} #${i + 1}: ${article.headline}`);
    lines.push(`**Source:** ${article.source || 'Unknown'}${article.author ? ` · ${article.author}` : ''}${article.publishedDate ? ` · ${formatDate(article.publishedDate)}` : ''}`);
    lines.push(`**Category:** ${article.category || 'General'} · **Urgency:** ${article.urgency || 'FYI'} · **Impact:** ${article.impact_score}/10`);
    lines.push('');
    lines.push(article.summary || '');
    lines.push('');
    lines.push('### 💡 What This Means for PPC Teams');
    lines.push(article.impact_analysis || '');
    lines.push('');
    lines.push(`[→ Read the full article](${article.url})`);
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // More stories — compact one-liners
  if (moreArticles.length > 0) {
    lines.push('## More Stories');
    lines.push('');

    for (let i = 0; i < moreArticles.length; i++) {
      const article = moreArticles[i];
      const n = i + 4;
      lines.push(`### #${n}: ${article.headline} (Score: ${article.impact_score}/10)`);
      lines.push(`${article.summary ? article.summary.split('.')[0] + '.' : ''} · ${article.source || ''} · [→ Read](${article.url})`);
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  // Source warnings
  if (meta.sourceWarnings && meta.sourceWarnings.length > 0) {
    lines.push('## ⚙️ Source Health');
    lines.push('');
    for (const warning of meta.sourceWarnings) {
      lines.push(`- ${warning}`);
    }
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // Footer
  const sourceSummary = sourceNames.length > 0
    ? `Sources: ${sourceNames.slice(0, 5).join(', ')}${sourceNames.length > 5 ? ` and ${sourceNames.length - 5} others` : ''}`
    : 'Multiple sources';
  lines.push(`*Generated by SEM Intel Agent · ${sourceSummary}*`);

  return lines.join('\n');
}

module.exports = { generateMarkdownPost };
